name: Update Gist

on:
  push:
    branch: master

  # schedule:
  #   - cron: "0 */3 * * *"

jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install
        run: npm ci
      - name: Update gist
        run: node ./index.js  --unhandled-rejections=strict
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: 7ff752e1f27bf1897de7e39f038a4077
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
